### ISSUE TITLE
Can I remove other person's voice

### ISSUE THREAD

**Issue by ILG2021** [EtienneAb3d/WhisperHallu#10]
Sometimes when I am using whisper for real time transcribe, someone else will speak in my room, then whisper will transcribe their voice also. It is a headache. And I want to remove other person's voice. Can anyone gives some suggestion?

**Comment by EtienneAb3d** [comment]
@ILG2021,
See these discussions:
https://github.com/openai/whisper/discussions?discussions_q=diarization

**Comment by ILG2021** [comment]
Thank you for your reply.
