### ISSUE TITLE
LoadModel fails if Whisper standard not installed

### ISSUE THREAD

**Issue by dgoryeo** [EtienneAb3d/WhisperHallu#2]
Hi @EtienneAb3d , in an attempt to use faster_whisper I omitted installing statndard Whisper. I get the following error from load model function:

[/content/WhisperHallu/transcribeHallu.py](https://localhost:8080/#) in loadModel(gpu, modelSize)
     58     global model
     59     device="cuda" #cuda cpu
---> 61     if isFaster:
     62         if(modelSize == "large"):

NameError: name 'isFaster' is not defined

**Comment by EtienneAb3d** [comment]
@dgoryeo This occurred for me when I forgot to convert standard models to Faster models in the Faster installation procedure. Or, perhaps the Faster model is at a place where it didn't find it.

**Comment by dgoryeo** [comment]
I used the following code (im collab) to install faster_Whisper. Perhap did I go wrong somewhere?


`!rm -rf faster-whisper
!git clone https://github.com/guillaumekln/faster-whisper.git

%cd faster-whisper
!pip install -e .[conversion]
#!pip install -e .

%cd ..

`

**Comment by EtienneAb3d** [comment]
You missed the conversion section. For the medium model:
`ct2-transformers-converter --model openai/whisper-medium --output_dir whisper-medium-ct2 --quantization float16`

**Comment by EtienneAb3d** [comment]
I think you need to do this after all commands you did, so that the model folder is in the current location when you run WhisperHallu.

**Comment by dgoryeo** [comment]
@EtienneAb3d , yes I was missing the conversion code. I'm still working on correctly installing faster-whipser. I'll let you know how it goes. Menawhile on a different note, is there a typo on line 79  --->    printl("Can't load Whisper model: "+modelSize) ?

**Comment by EtienneAb3d** [comment]
@dgoryeo, you are right. Fixed.
I also fixed the `exit` lines that wasn't execute correctly.

You install problem is perhaps your `cd` command.
You should try the python command instead:

```
os.chdir("faster-whisper")
!pip install -e .[conversion]
!pip install -e .
os.chdir("..")

!ct2-transformers-converter --model openai/whisper-medium --output_dir whisper-medium-ct2 --quantization float16
```

**Comment by stevevaius2015** [comment]
Could you provide a full Colab notebook for faster-whisper library. Looks amazing possibilities there by your effort.

**Comment by EtienneAb3d** [comment]
@stevevaius2015, here it is:
https://colab.research.google.com/drive/1RkvOtUTbUD5NVsRI4aKEqJO8BRo8BFIY?usp=sharing
;-)
