### ISSUE TITLE
Google Colab Error

### ISSUE THREAD

**Issue by mad1m** [EtienneAb3d/WhisperHallu#22]
Hey,
the Google Colab "Standard Whisper" doesn't work anymore.
getting the following error.
`[/usr/local/lib/python3.10/dist-packages/torchaudio/_extension/utils.py](https://localhost:8080/#) in _check_cuda_version()
    190         t_version = f"{t_version[0]}.{t_version[1]}"
    191         if ta_version != t_version:
--> 192             raise RuntimeError(
    193                 "Detected that PyTorch and TorchAudio were compiled with different CUDA versions. "
    194                 f"PyTorch has CUDA version {t_version} whereas TorchAudio has CUDA version {ta_version}. "

RuntimeError: Detected that PyTorch and TorchAudio were compiled with different CUDA versions. PyTorch has CUDA version 12.1 whereas TorchAudio has CUDA version 11.8. Please install the TorchAudio version that matches your PyTorch version.`

**Comment by EtienneAb3d** [comment]
@mad1m 
Sorry for the delay..
I just took the time to test it. 
All seems to work properly now.
;-)

**Comment by mad1m** [comment]
Thanks! it works now
