### ISSUE TITLE
Use FFMPEG silenceremove and VAD

### ISSUE THREAD

**Issue by sorgfresser** [EtienneAb3d/WhisperHallu#5]
Wonderful pipeline, thanks a lot for your great work! It was a bit painful to set up in my case but now it works like a charm. Still I am curious about the usage of silenceremove and VAD together. Shouldn't silero-vad be capable of doing silenceremove's job too?
Surely I am mistaken and there is a good reason, I just want to know which.

**Comment by EtienneAb3d** [comment]
I @sorgfresser,
Thanks for your positive feedback!
Yes, VAD is supposed to be able to remove pure silences, but it doesn't.
Using both ensure a better silence+noise removal. 
It's especially important since hallucinations often occur on silences.
;-)

**Comment by sorgfresser** [comment]
Thanks a lot!
