### ISSUE TITLE
GPU out of memory 

### ISSUE THREAD

**Issue by ILG2021** [EtienneAb3d/WhisperHallu#8]
I have a 8G gpu, sometimes it will crash as out of memory. How to reduce the cost of memory?

**Comment by EtienneAb3d** [comment]
@ILG2021,

First of all, are you using Fast Whisper in place of Standard Whisper? This is the main way to get a smaller (and faster) model, without loss in quality.

You may try to use Spleeter in place of Demucs, but it's a bit less efficient.

Both Demucs and Whisper are loaded at the same time. There is perhaps a way to unload one while the other is in use, but I never experiment with this at this time.

You may also change the code to have one of them with CPU processing, but this could take a much larger time.

**Comment by ILG2021** [comment]
I am using faster_whisper. The Demucs offical github said, If you have a GPU, but you run out of memory, please use --segment SEGMENT to reduce length of each split. SEGMENT should be changed to a integer. How can I set segment in your code?

**Comment by ILG2021** [comment]
ok, thank you.

**Comment by ILG2021** [comment]
can you release your project as a pip package? It is very valuable for whom using whisper. Like whisper-noise-reducer. And there are pipelines that can use vad, Demucs, Spleeter, ffmpeg, marker that we can use one or more of them. I have used faster_whisper built-in vad and integrate demucs and ffmpeg, it works amazing. Thanks for your project.

**Comment by EtienneAb3d** [comment]
@ILG2021,
Thanks for your positive feedback!
As said on the main page, at start this code was a pure experimental one, to test some ideas. It wasn't really designed to be released as a well packaged solution.
I will investigate on the procedure to release it as a pip package.

**Comment by EtienneAb3d** [comment]
> Both Demucs and Whisper are loaded at the same time. There is perhaps a way to unload one while the other is in use, but I never experiment with this at this time.

Here is a discussion linked to that subject:
https://github.com/openai/whisper/discussions/1313#discussioncomment-5813140
