### ISSUE TITLE
RAM Exceedance on Google Colab Handling Long Audio

### ISSUE THREAD

**Issue by CarlNs92891** [EtienneAb3d/WhisperHallu#9]
The standard Google Colab notebook crashes with a ~40 mins audio file, as it use up the RAM during voice extraction with demucs. Could we prevent this by not loading the Whisper model until demucs finishes?

**Comment by EtienneAb3d** [comment]
@CarlNs92891,
At this time, I don't know how to unload one while the other is loaded.
See possible modifications to test, here:
https://github.com/EtienneAb3d/WhisperHallu/issues/8

**Comment by ILG2021** [comment]
use faster_whisper and int8 inference can solve your problem.

**Comment by CarlNs92891** [comment]
Thanks! @ILG2021 Can confirm it works on 43 mins long audio.
